### ISSUE TITLE
Remembering login across restarts

### ISSUE THREAD

**Issue by trypsynth** [cartertemm/audiovault-downloader#2]
It can get quite annoying having to re-login after every launch of the program. It would be nice if it could remember your login across restarts. This could possibly be optional, and I'm also not sure how to best store it (env vars, a tiny ConfigObj, etc), so figured I'd open an issue first before possibly trying to tackle it.

**Comment by cartertemm** [comment]
Hi,

First off, thanks for your interest. I've on multiple occasions considered such a feature but never got around to writing code for it.

Since most of our users are not programmers, we should probably stay away from environment variables. Also given that credentials will presumably be stored in plain text, the feature needs to be entirely optional to promote security.

I always envisioned an uncomplicated single text file delineated by username and password. This way it can be read by the program just as easily as someone who forgot their password. However, I have no preference for the format, save an endeavor to require as few external modules as possible. In other words, `configparser` over `configobj` if you do wish to go that route.

Hopefully this provides a bit more direction. Happy to elaborate or throw around more ideas should they prove useful.

**Comment by trypsynth** [comment]
@cartertemm,
I have forked this repo and began working. I have auto login fully working, at least from my testing.
The one thing I'm not exactly sure how to handle is asking if the user wants to save the login. A prompt every time after logging in might be slightly annoying for some users, but I really don't know how else to do it. We have no GUI to deal with, so no checkboxs or anything else like that.
Thoughts?

**Comment by cartertemm** [comment]
It should be sufficient to ask only once on first login, so long as users are made aware of this. If you like you can submit a PR and I will review.

**Comment by trypsynth** [comment]
see #3
